# tessyfarm_smartloop/docker-compose.yml
version: '3.8'

services:
  # Backend API (FastAPI) - (existing service definition)
  backend_api:
    build: ./backend_api
    # ... (rest of backend_api config) ...
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      mqtt_broker: # Added explicit dependency
        condition: service_started

  # Database (PostgreSQL) - (existing service definition)
  db:
    image: postgres:15-alpine
    # ... (rest of db config) ...
    env_file:
      - ./.env

  # MQTT Broker (Mosquitto) - (existing service definition)
  mqtt_broker:
    image: eclipse-mosquitto:2
    # ... (rest of mqtt_broker config) ...

  # NEW: IoT Listener Service
  iot_listener:
    build: ./iot_listener
    container_name: tessyfarm_iot_listener
    env_file:
      - ./.env # To get DB and MQTT connection details
    depends_on:
      db: # Depends on the database being healthy
        condition: service_healthy
      mqtt_broker: # Depends on the MQTT broker being started
        condition: service_started
    restart: unless-stopped # Or always, depending on your preference

volumes:
  postgres_data:

networks:
  default:
    driver: bridge

