# tessyfarm_smartloop/docker-compose.yml
services:
  backend_api:
    build: ./backend_api
    container_name: tessyfarm_backend_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend_api:/app # For live reload of backend code
      - ./ml_models:/app/ml_models # Mount ml_models directory
    env_file:
      - ./.env
    depends_on:
      # ...
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


  # Database (PostgreSQL) - (existing service definition)
  db:
    image: postgres:15-alpine
    # ... (rest of db config) ...
    env_file:
      - ./.env

  # MQTT Broker (Mosquitto) - (existing service definition)
  mqtt_broker:
    image: eclipse-mosquitto:2
    # ... (rest of mqtt_broker config) ...

  # NEW: IoT Listener Service
  iot_listener:
    build: ./iot_listener
    container_name: tessyfarm_iot_listener
    env_file:
      - ./.env # To get DB and MQTT connection details
    depends_on:
      db: # Depends on the database being healthy
        condition: service_healthy
      mqtt_broker: # Depends on the MQTT broker being started
        condition: service_started
    restart: unless-stopped # Or always, depending on your preference

volumes:
  postgres_data:

networks:
  default:
    driver: bridge

