# tessyfarm_smartloop/docker-compose.yml
version: '3.8'

services:
  # ... backend_api, db, mqtt_broker, iot_listener, cron_scheduler ...

  frontend_dashboard:
    build:
      context: ./frontend_dashboard
      dockerfile: Dockerfile.dev # Use the development Dockerfile
    container_name: tessyfarm_frontend
    ports:
      - "5173:5173" # Vite's default port
    volumes:
      - ./frontend_dashboard:/app          # Mount app code for hot reloading
      - /app/node_modules                 # Anonymous volume to prevent host node_modules overwriting container's
    restart: unless-stopped
    depends_on:
      - backend_api # Frontend usually depends on backend being available
    environment:
      # Vite uses this env var to point to the backend if proxied or for direct calls
      # If your api.js uses an absolute URL like http://localhost:8000, this isn't strictly needed by Vite itself
      # but can be useful for configuring the app.
      - VITE_API_BASE_URL=http://localhost:8000/api/v1 
      # Ensure your React app reads this. Vite automatically exposes VITE_ vars to import.meta.env

# ... volumes, networks ...
